### ISSUE TITLE
swnn.groupwise_hvgs_freq KeyError: '[nan] not in index'

### ISSUE THREAD

**Issue by grimwoo** [XingyanLiu/stagewiseNN#1]
hi , thanks for the development of stagewiseNN.
here I encountered an error when using swnn.groupwise_hvgs_freq().
my object  was transformed from a package named Seurat in R with "SaveH5Seurat()" function and it (adata) could be processed correctly in Scanpy. Hence , I guess the error may be trigger by the "integrated" assay in Seurat. However , the warning information and error information was the same when using 'RNA' assay.
  
Could anyone help me?
  
**_>>> adata_**
AnnData object with n_obs × n_vars = 107289 × 2000
    obs: 'species', 'celltype2', 'time.sum2', 'ReorderIdent', 'celltype.merge2', 'nCount_RNA', 'nFeature_RNA', 'nCount_integrated', 'nFeature_integrated', 'time.sum2_cat'
    var: 'features'
    uns: 'log1p'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
  
**### >>> adata = swnn.normalize_default(adata, target_sum=None, copy=True, )**
D:\system_software\Miniconda3\envs\stagewiseNN\lib\site-packages\scanpy\preprocessing\_normalization.py:197: UserWarning: Some cells have zero counts
  warn(UserWarning('Some cells have zero counts'))
D:\system_software\Miniconda3\envs\stagewiseNN\lib\site-packages\scanpy\preprocessing\_simple.py:352: RuntimeWarning: invalid value encountered in log1p
  np.log1p(X, out=X)
  
**### >>> hvg_freq, hvg_dict = swnn.groupwise_hvgs_freq(adata, groupby='time.sum2_cat')**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\system_software\Miniconda3\envs\stagewiseNN\lib\site-packages\swnn\utils\process.py", line 200, in groupwise_hvgs_freq
    sc.pp.highly_variable_genes(_adt, **hvg_kwds)
  File "D:\system_software\Miniconda3\envs\stagewiseNN\lib\site-packages\scanpy\preprocessing\_highly_variable_genes.py", line 434, in highly_variable_genes
    df = _highly_variable_genes_single_batch(
  File "D:\system_software\Miniconda3\envs\stagewiseNN\lib\site-packages\scanpy\preprocessing\_highly_variable_genes.py", line 223, in _highly_variable_genes_single_batch
    gen_indices = np.where(one_gene_per_bin[df['mean_bin'].values])[0].tolist()
  File "D:\system_software\Miniconda3\envs\stagewiseNN\lib\site-packages\pandas\core\series.py", line 984, in __getitem__
    return self._get_with(key)
  File "D:\system_software\Miniconda3\envs\stagewiseNN\lib\site-packages\pandas\core\series.py", line 1024, in _get_with
    return self.loc[key]
  File "D:\system_software\Miniconda3\envs\stagewiseNN\lib\site-packages\pandas\core\indexing.py", line 967, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "D:\system_software\Miniconda3\envs\stagewiseNN\lib\site-packages\pandas\core\indexing.py", line 1191, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "D:\system_software\Miniconda3\envs\stagewiseNN\lib\site-packages\pandas\core\indexing.py", line 1132, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "D:\system_software\Miniconda3\envs\stagewiseNN\lib\site-packages\pandas\core\indexing.py", line 1327, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
  File "D:\system_software\Miniconda3\envs\stagewiseNN\lib\site-packages\pandas\core\indexes\base.py", line 5782, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "D:\system_software\Miniconda3\envs\stagewiseNN\lib\site-packages\pandas\core\indexes\base.py", line 5845, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: '[nan] not in index'

**Comment by grimwoo** [comment]
When I changed the python from 3.8 to 3.6, the error information changed:

**>>> hvg_freq, hvg_dict = swnn.groupwise_hvgs_freq(adata, groupby='time.sum2_cat')**
/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN_old/lib/python3.6/site-packages/scanpy/preprocessing/_highly_variable_genes.py:208: RuntimeWarning: invalid value encountered in log
  dispersion = np.log(dispersion)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN_old/lib/python3.6/site-packages/swnn/utils/process.py", line 200, in groupwise_hvgs_freq
    sc.pp.highly_variable_genes(_adt, **hvg_kwds)
  File "/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN_old/lib/python3.6/site-packages/scanpy/preprocessing/_highly_variable_genes.py", line 440, in highly_variable_genes
    flavor=flavor,
  File "/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN_old/lib/python3.6/site-packages/scanpy/preprocessing/_highly_variable_genes.py", line 223, in _highly_variable_genes_single_batch
    gen_indices = np.where(one_gene_per_bin[df['mean_bin'].values])[0].tolist()
  File "/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN_old/lib/python3.6/site-packages/pandas/core/series.py", line 906, in __getitem__
    return self._get_with(key)
  File "/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN_old/lib/python3.6/site-packages/pandas/core/series.py", line 946, in _get_with
    return self.loc[key]
  File "/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN_old/lib/python3.6/site-packages/pandas/core/indexing.py", line 879, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN_old/lib/python3.6/site-packages/pandas/core/indexing.py", line 1099, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN_old/lib/python3.6/site-packages/pandas/core/indexing.py", line 1037, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis, raise_missing=False)
  File "/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN_old/lib/python3.6/site-packages/pandas/core/indexing.py", line 1240, in _get_listlike_indexer
    indexer, keyarr = ax._convert_listlike_indexer(key)
  File "/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN_old/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3216, in _convert_listlike_indexer
    indexer = self._convert_list_indexer(keyarr)
  File "/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN_old/lib/python3.6/site-packages/pandas/core/indexes/category.py", line 598, in _convert_list_indexer
    indexer = self.categories._convert_list_indexer(keyarr)
  File "/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN_old/lib/python3.6/site-packages/pandas/core/indexes/interval.py", line 533, in _convert_list_indexer
    raise KeyError
KeyError

**Comment by XingyanLiu** [comment]
This error may due to a bug in scanpy's build-in function 'sc.pp.highly_variable_genes', where you can either (1) fix this bug by yourself (see below ⬇️ ) or (2) set the parameter 'n_top_genes' as a specific number (e.g., 2000).

To fix the bug, open the file '{PYTHON_OR_CONDA_PATH}/envs/{ENV_NAME}/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py', delete (or comment) the line 514-515, and add a new line as below 'df.dispersions_norm[df.dispersions_norm.isna()] = 0'.

<img width="499" alt="image" src="https://user-images.githubusercontent.com/23734945/176351633-4b339127-4623-4920-86a3-11d7a17d2f8d.png">

**Comment by grimwoo** [comment]
@XingyanLiu Thanks for your quick response. I have changed the "_highly_variable_genes.py" file and set the parameter 'n_top_genes' as a specific number (e.g., 2000). However, a new error shows.

![image](https://user-images.githubusercontent.com/49429496/177090437-b30d32bc-bd7a-455c-8c50-107d916e6b51.png)

**>>> hvg_freq, hvg_dict = swnn.groupwise_hvgs_freq(adata, groupby='time.sum2_cat', n_top_genes=2000)**
/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:200: RuntimeWarning: invalid value encountered in expm1
  X = np.expm1(X)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN/lib/python3.8/site-packages/swnn/utils/process.py", line 200, in groupwise_hvgs_freq
    sc.pp.highly_variable_genes(_adt, **hvg_kwds)
  File "/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py", line 434, in highly_variable_genes
    df = _highly_variable_genes_single_batch(
  File "/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py", line 215, in _highly_variable_genes_single_batch
    df['mean_bin'] = pd.cut(df['means'], bins=n_bins)
  File "/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN/lib/python3.8/site-packages/pandas/core/reshape/tile.py", line 292, in cut
    fac, bins = _bins_to_cuts(
  File "/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN/lib/python3.8/site-packages/pandas/core/reshape/tile.py", line 419, in _bins_to_cuts
    raise ValueError(
ValueError: Bin edges must be unique: array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan]).
You can drop duplicate edges by setting the 'duplicates' kwarg
  
  
  
**>>> hvg_freq, hvg_dict = swnn.groupwise_hvgs_freq(adata, groupby='time.sum2_cat')**
/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:200: RuntimeWarning: invalid value encountered in expm1
  X = np.expm1(X)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN/lib/python3.8/site-packages/swnn/utils/process.py", line 200, in groupwise_hvgs_freq
    sc.pp.highly_variable_genes(_adt, **hvg_kwds)
  File "/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py", line 434, in highly_variable_genes
    df = _highly_variable_genes_single_batch(
  File "/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py", line 215, in _highly_variable_genes_single_batch
    df['mean_bin'] = pd.cut(df['means'], bins=n_bins)
  File "/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN/lib/python3.8/site-packages/pandas/core/reshape/tile.py", line 292, in cut
    fac, bins = _bins_to_cuts(
  File "/mnt/c/Users/grimw/CELLECT/enter/envs/stagewiseNN/lib/python3.8/site-packages/pandas/core/reshape/tile.py", line 419, in _bins_to_cuts
    raise ValueError(
ValueError: Bin edges must be unique: array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan]).
You can drop duplicate edges by setting the 'duplicates' kwarg

**Comment by XingyanLiu** [comment]
The problem is caused by "the h5ad files converted from seurat-object by SeuratDisk".  If you used StagewiseNN to process the data from the raw-count matrices, please use scanpy to construct the AnnData object from the raw-count matrices (e.g., the *.mtx and *.txt files)

You can also use the following R code to export the filtered scRNA-seq data
into an .h5 file, which takes less time and space.

```R
# R code
library(rhdf5)
library(Matrix)

save_h5mat = function(mat, fp_h5, feature_type, genome=""){
# =============== Test code ===============
# tmp = Seurat::Read10X_h5(fp_h5)
# all(tmp@x == mat@x)
# all(tmp@i == mat@i)
# all(tmp@p == mat@p)
#
# save sparse.mat ('dgCMatrix' format) into a h5 file
message(fp_h5)

h5createFile(fp_h5)
root = "matrix"
h5createGroup(fp_h5, root)

h5write(dim(mat), fp_h5, paste(root, "shape", sep='/'))
h5write(mat@x, fp_h5, paste(root, "data", sep='/'))
h5write(mat@i, fp_h5, paste(root, "indices", sep='/'))  # mat@i - 1 ?
h5write(mat@p, fp_h5, paste(root, "indptr", sep='/'))
h5write(colnames(mat), fp_h5, paste(root, "barcodes", sep='/'))


feat_root = paste(root, "features", sep='/')
h5createGroup(fp_h5, feat_root)

h5write(rownames(mat), fp_h5, paste(feat_root, "id", sep='/'))
h5write(rownames(mat), fp_h5, paste(feat_root, "name", sep='/'))

h5write(rep(feature_type, dim(mat)[1]),
      fp_h5, paste(feat_root, "feature_type", sep='/'))

h5write(rep("", dim(mat)[1]),
      fp_h5, paste(feat_root, "derivation", sep='/'))
h5write(rep(genome, dim(mat)[1]),  # "mm10"
      fp_h5, paste(feat_root, "genome", sep='/'))
h5write(c("genome", "derivation"),
      fp_h5, paste(feat_root, "_all_tag_keys", sep='/'))

h5closeAll()
message("Done!")
}

# save_h5mat_peak = function(mat, fp_h5, genome=""){
#   save_h5mat(mat, fp_h5, feature_type = "Peaks", genome = genome)
# }

save_h5mat_gex = function(mat, fp_h5, genome=""){
save_h5mat(mat, fp_h5, feature_type = "Gene Expression", genome = genome)
}

# save the raw-counts in a Seurat-object "seurat_obj":
mat = seurat_obj[["RNA"]]@counts
save_h5mat_gex(mat, "matrix.raw.h5", genome="")

# save the meta-data into a csv file:
meta_data = seurat_obj@meta.data
write.csv(meta_data, "metadata.csv")
```

And read the h5 file using Scanpy's build-in function:

```python
# python-code
import pandas as pd
import scanpy as sc
fp_mat = 'matrix.raw.h5'
fp_meta = 'metadata.csv'
adata_raw = sc.read_10x_h5(fp_mat)
metadata = pd.read_csv(fp_meta, index_col=0)
for c in metadata.columns:
    adata_raw.obs[c] = metadata[c]
```

Hope it helps!
